# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('iddeposito', models.IntegerField(db_column='idDeposito', primary_key=True, serialize=False)),
                ('deposito', models.CharField(max_length=30)),
                ('latitud', models.CharField(blank=True, max_length=15, null=True)),
                ('longitud', models.CharField(blank=True, max_length=15, null=True)),
                ('gerentedeposito', models.CharField(blank=True, db_column='gerenteDeposito', max_length=45, null=True)),
                ('jefeentrega', models.CharField(blank=True, db_column='jefeEntrega', max_length=45, null=True)),
                ('operadorsistema', models.CharField(blank=True, db_column='operadorSistema', max_length=45, null=True)),
                ('telefonoext', models.CharField(blank=True, db_column='telefonoExt', max_length=45, null=True)),
                ('correogd', models.CharField(blank=True, db_column='correoGD', max_length=45, null=True)),
                ('correoje', models.CharField(blank=True, db_column='correoJE', max_length=45, null=True)),
                ('correoop', models.CharField(blank=True, db_column='correoOP', max_length=45, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('total_vpp', models.IntegerField(blank=True, null=True)),
                ('total_ppp', models.IntegerField(blank=True, null=True)),
                ('total_av', models.IntegerField(blank=True, null=True)),
                ('diferenciahoraria', models.IntegerField(blank=True, db_column='diferenciaHoraria', null=True)),
            ],
            options={
                'db_table': 'deposito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paletizador',
            fields=[
                ('idpaletizador', models.AutoField(primary_key=True, serialize=False)),
                ('iddeposito', models.IntegerField(unique=True)),
                ('largotarima', models.IntegerField()),
                ('anchotarima', models.IntegerField(blank=True, null=True)),
                ('margen', models.IntegerField()),
                ('margen1', models.IntegerField(blank=True, null=True)),
                ('tipotarima1', models.CharField(blank=True, max_length=45, null=True)),
                ('tipotarima2', models.CharField(blank=True, max_length=45, null=True)),
                ('tipotarima3', models.CharField(blank=True, max_length=45, null=True)),
                ('tipotarima4', models.CharField(blank=True, max_length=45, null=True)),
                ('tipotarima5', models.CharField(blank=True, max_length=45, null=True)),
                ('porcentaje_completa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_bandera', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_escuadra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_combinada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku_garrafon', models.CharField(blank=True, max_length=60, null=True)),
                ('calculo_x_pasillos', models.IntegerField(db_column='Calculo_X_Pasillos')),
            ],
            options={
                'db_table': 'paletizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.AutoField(db_column='idRegion', primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=45)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=45, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idzona', models.AutoField(db_column='idZona', primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=45)),
                ('gerentezona', models.CharField(db_column='gerenteZona', max_length=45)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
